version: '3.1'
services:
    app:
      image: grafana/grafana:latest
      ports:
        - 3000:3000
      volumes:
        - app:/var/lib/grafana
      restart: unless-stopped
    influxdb:
      image: influxdb:latest
      ports:
        - 8086:8086
      volumes:
        - db:/var/lib/influxdb
        - db2:/var/lib/influxdb2
        - db_etc:/etc/influxdb2
      environment:
        - INFLUXDB_DB=grafana
      restart: unless-stopped
volumes:
  app:
  db:
  db2:
  db_etc:
